POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "type": "HealthCheck",
  "date": "2019-10-20",
  "specialist": "MD Morty",
  "description": "que locura chaval",
  "healthCheckRating": 3
}

###

POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "type": "Hospital",
  "date": "2019-10-10",
  "specialist": "MD Budin",
  "description": "que locura ",
  "diagnosisCodes": ["S62.5","Z57.1"],
  "discharge": {
    "date": "2015-02-16",
    "criteria": "criteriaaa"
  }
}

###

POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "type": "OccupationalHealthcare",
  "date": "2019-10-10",
  "specialist": "MD Budin",
  "description": "que locura ",
  "employerName": "HyPD",
  "diagnosisCodes": ["S62.5","Z57.1"],
  "sickLeave": {
    "startDate": "2019-08-05",
    "endDate": "2019-08-28"
  }
}